# Generated by Django 4.2.2 on 2023-06-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrementvocal',
            name='fichier_audio',
            field=models.FileField(upload_to='enregistrements'),
        ),
    ]
